/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;



import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import javax.swing.JDialog;
import java.awt.PopupMenu;
import java.awt.event.ActionListener;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Hoang Truong
 */
public class ChamCongCongNhan extends javax.swing.JPanel {

    private PopupMenu QuanLyCN;

    /**
     * Creates new form ChamCongCongNhan
     */
    public ChamCongCongNhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblNgayChamCong = new javax.swing.JLabel();
        lblSoLuongSanPham = new javax.swing.JLabel();
        lblMaCongNhan = new javax.swing.JLabel();
        lblTenCongDoanRight = new javax.swing.JLabel();
        lblTenSanPhamRight = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        lblMaCongDoan = new javax.swing.JLabel();
        lblCaLam = new javax.swing.JLabel();
        lblMaSanPham = new javax.swing.JLabel();
        lblTenSanPham = new javax.swing.JLabel();
        lblTenCongDoan = new javax.swing.JLabel();
        lblToNhom = new javax.swing.JLabel();
        lblMaCongNhan1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTenSanPhamRight1 = new javax.swing.JLabel();
        lblTenSanPhamRight2 = new javax.swing.JLabel();
        cboCaLam = new javax.swing.JComboBox<>();
        cmbTinhTrang = new javax.swing.JComboBox<>();
        btnLayDSPhanCong = new javax.swing.JButton();
        txtMaSanPham = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        txtMaCongDoan = new javax.swing.JTextField();
        txtTenCongDoan = new javax.swing.JTextField();
        cmbCaLam = new javax.swing.JComboBox<>();
        txtSoLuongLam = new javax.swing.JTextField();
        txtTenCongNhan = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtMaCongNhan = new javax.swing.JTextField();
        txtMaCongDoan2 = new javax.swing.JTextField();
        txtTenCongDoan2 = new javax.swing.JTextField();
        txtMaSanPham2 = new javax.swing.JTextField();
        txtTenSanPham2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dtNgayChamCong = new com.toedter.calendar.JDateChooser();
        lblNguoiChamCong = new javax.swing.JLabel();
        txtSoLuongLam1 = new javax.swing.JTextField();
        pnlChucNangTo = new javax.swing.JPanel();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        scrChamCong = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel5.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayChamCong.setText("Ngày chấm công:");
        jPanel5.add(lblNgayChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 140, 40));

        lblSoLuongSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoLuongSanPham.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoLuongSanPham.setText("Số lượng làm:");
        jPanel5.add(lblSoLuongSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 250, -1, 40));

        lblMaCongNhan.setBackground(new java.awt.Color(255, 255, 255));
        lblMaCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaCongNhan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaCongNhan.setText("Tên công nhân:");
        jPanel5.add(lblMaCongNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 160, 40));

        lblTenCongDoanRight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenCongDoanRight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenCongDoanRight.setText("Tên sản phẩm:");
        jPanel5.add(lblTenCongDoanRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 210, -1, 40));

        lblTenSanPhamRight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenSanPhamRight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenSanPhamRight.setText("Mã công đoạn:");
        jPanel5.add(lblTenSanPhamRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 90, 122, 40));

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrangThai.setText("Tình trạng:");
        jPanel5.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 90, 40));

        lblMaCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaCongDoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaCongDoan.setText("Mã công đoạn:");
        jPanel5.add(lblMaCongDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        lblCaLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaLam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCaLam.setText("Ca làm:");
        lblCaLam.setToolTipText("");
        jPanel5.add(lblCaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 40));

        lblMaSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaSanPham.setText("Mã sản phẩm:");
        jPanel5.add(lblMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        lblTenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenSanPham.setText("Tên sản phẩm:");
        jPanel5.add(lblTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        lblTenCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenCongDoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenCongDoan.setText("Tên công đoạn:");
        jPanel5.add(lblTenCongDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 40));

        lblToNhom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblToNhom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblToNhom.setText("Tổ:");
        jPanel5.add(lblToNhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 40, 40));

        lblMaCongNhan1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaCongNhan1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaCongNhan1.setText("Mã công nhân:");
        jPanel5.add(lblMaCongNhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ca làm:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        lblTenSanPhamRight1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenSanPhamRight1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenSanPhamRight1.setText("Tên công đoạn:");
        jPanel5.add(lblTenSanPhamRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 130, -1, 40));

        lblTenSanPhamRight2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenSanPhamRight2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenSanPhamRight2.setText("Mã sản phẩm:");
        jPanel5.add(lblTenSanPhamRight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 170, -1, 40));

        cboCaLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Chiều", "Tối" }));
        jPanel5.add(cboCaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 120, 30));

        cmbTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đi đúng giờ", "Đi trễ", "Nghỉ có phép", "Nghỉ không phép" }));
        jPanel5.add(cmbTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 150, 30));

        btnLayDSPhanCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLayDSPhanCong.setText("Lấy danh sách phân công");
        btnLayDSPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLayDSPhanCongMouseClicked(evt);
            }
        });
        btnLayDSPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayDSPhanCongActionPerformed(evt);
            }
        });
        jPanel5.add(btnLayDSPhanCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 250, 40));

        txtMaSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaSanPham.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, 30));

        txtTenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenSanPham.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, 30));

        txtMaCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaCongDoan.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtMaCongDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 30));

        txtTenCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenCongDoan.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTenCongDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 30));

        cmbCaLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Chiều", "Tối" }));
        jPanel5.add(cmbCaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 120, 30));

        txtSoLuongLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoLuongLam.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtSoLuongLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 260, 260, 30));

        txtTenCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenCongNhan.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTenCongNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 260, 30));

        txtTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTo.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 260, 30));

        txtMaCongNhan.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        txtMaCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(txtMaCongNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 260, 30));

        txtMaCongDoan2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaCongDoan2.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtMaCongDoan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 260, 30));

        txtTenCongDoan2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenCongDoan2.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTenCongDoan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 140, 260, 30));

        txtMaSanPham2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaSanPham2.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtMaSanPham2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 180, 260, 30));

        txtTenSanPham2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenSanPham2.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtTenSanPham2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 220, 260, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CHẤM CÔNG CÔNG NHÂN");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1760, 50));

        dtNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(dtNgayChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 260, 30));

        lblNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNguoiChamCong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNguoiChamCong.setText("Người chấm công:");
        jPanel5.add(lblNguoiChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, -1, 40));

        txtSoLuongLam1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoLuongLam1.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        jPanel5.add(txtSoLuongLam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 300, 260, 30));

        pnlChucNangTo.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNangTo.setLayout(new java.awt.BorderLayout());

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNang.setPreferredSize(new java.awt.Dimension(698, 57));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTimKiem))
                .addContainerGap())
        );

        pnlChucNangTo.add(pnlChucNang, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlChucNangTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 580, -1));

        scrChamCong.setBackground(new java.awt.Color(255, 255, 255));
        scrChamCong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng chấm công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        tblChamCong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã chấm công", "Mã công nhân", "Họ và tên", "Tổ", "Ngày chấm công", "Ca làm", "Tình trạng", "Mã công đoạn", "Tên Công đoạn", "Mã sản phẩm", "Tên Sản phẩm", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamCong.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblChamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamCongMouseClicked(evt);
            }
        });
        scrChamCong.setViewportView(tblChamCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, 1748, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblChamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamCongMouseClicked

    }//GEN-LAST:event_tblChamCongMouseClicked

    private void btnLayDSPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLayDSPhanCongMouseClicked
        JDialog layDsPhanCong = new JDialog();
        layDsPhanCong.add(new LayDSChamCongCN());
        layDsPhanCong.setTitle("Danh sách phân công công nhân");
        layDsPhanCong.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        layDsPhanCong.setSize(1200, 700);
        layDsPhanCong.setLocationRelativeTo(null);
        layDsPhanCong.setVisible(true);
    }//GEN-LAST:event_btnLayDSPhanCongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        pnlChucNangTo.removeAll();
        pnlChucNangTo.setLayout(new BorderLayout());
        PanelXacNhan pnlXacNhan = new PanelXacNhan();
        pnlChucNangTo.add(pnlXacNhan);

        ActionListener listenerHuy = new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("ok");
                pnlChucNangTo.removeAll();
                pnlChucNangTo.setLayout(new BorderLayout());
                pnlChucNangTo.add(pnlChucNang);
                pnlChucNangTo.updateUI();
            }
        };
        pnlXacNhan.huyAddActionListener(listenerHuy);
        pnlChucNangTo.repaint();
        pnlChucNangTo.revalidate();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLayDSPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayDSPhanCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLayDSPhanCongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayDSPhanCong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboCaLam;
    private javax.swing.JComboBox<String> cmbCaLam;
    private javax.swing.JComboBox<String> cmbTinhTrang;
    private com.toedter.calendar.JDateChooser dtNgayChamCong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCaLam;
    private javax.swing.JLabel lblMaCongDoan;
    private javax.swing.JLabel lblMaCongNhan;
    private javax.swing.JLabel lblMaCongNhan1;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblNgayChamCong;
    private javax.swing.JLabel lblNguoiChamCong;
    private javax.swing.JLabel lblSoLuongSanPham;
    private javax.swing.JLabel lblTenCongDoan;
    private javax.swing.JLabel lblTenCongDoanRight;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblTenSanPhamRight;
    private javax.swing.JLabel lblTenSanPhamRight1;
    private javax.swing.JLabel lblTenSanPhamRight2;
    private javax.swing.JLabel lblToNhom;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlChucNangTo;
    private javax.swing.JScrollPane scrChamCong;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTextField txtMaCongDoan;
    private javax.swing.JTextField txtMaCongDoan2;
    private javax.swing.JTextField txtMaCongNhan;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtMaSanPham2;
    private javax.swing.JTextField txtSoLuongLam;
    private javax.swing.JTextField txtSoLuongLam1;
    private javax.swing.JTextField txtTenCongDoan;
    private javax.swing.JTextField txtTenCongDoan2;
    private javax.swing.JTextField txtTenCongNhan;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTenSanPham2;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
