/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author 1805v
 */
public class DoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMatKhauCu = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        lblXacNhanMatKhau = new javax.swing.JLabel();
        pwfMatKhauCu = new javax.swing.JPasswordField();
        pwfMatKhauMoi = new javax.swing.JPasswordField();
        pwfXacNhanMatKhau = new javax.swing.JPasswordField();
        btnHuy = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        lblMatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMatKhauCu.setText("Mật khẩu cũ:");
        add(lblMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lblMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMatKhauMoi.setText("Mật khẩu mới:");
        add(lblMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lblXacNhanMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblXacNhanMatKhau.setText("Xác nhận mật khẩu mới:");
        add(lblXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        pwfMatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwfMatKhauCu.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(pwfMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 180, -1));

        pwfMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwfMatKhauMoi.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(pwfMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 180, -1));

        pwfXacNhanMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwfXacNhanMatKhau.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(pwfXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 180, -1));

        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 180, -1));

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-mark.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed

    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatKhauCu;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblXacNhanMatKhau;
    private javax.swing.JPasswordField pwfMatKhauCu;
    private javax.swing.JPasswordField pwfMatKhauMoi;
    private javax.swing.JPasswordField pwfXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
