/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

import dao.DiaChiDAO;
import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import entity.DiaChi;
import entity.NhanVien;
import entity.TaiKhoan;
import setting.PathSetting;
import tablemodels.NhanVienTableModel;

/**
 *
 * @author Hoang Truong
 */
public class QuanLyNV extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNV
     */
	private NhanVienDAO nhanVienDAO;
    private NhanVienTableModel nhanVienTableModel;
    private DiaChiDAO diaChiDAO;
    private TaiKhoanDAO taiKhoanDAO;
    private List<NhanVien> dsNV;
    private boolean trangThaiThem;
    private static final String[] HEADERS = {"Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Email", "Số điện thoại", "Địa chỉ", "Ngày vào làm", "Giới tính", "Vai trò"};
    public QuanLyNV() {
    	nhanVienDAO = new NhanVienDAO();
    	diaChiDAO = new DiaChiDAO();
    	taiKhoanDAO = new TaiKhoanDAO();
    	trangThaiThem = false;
        initComponents();
        themSuKien();
        updateComboboxTinh();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //them su kien cho UI Quan Ly Nhan Vien
    private void updateModelTable(List<NhanVien> dsNV,String[] headers) {
    	nhanVienTableModel = new NhanVienTableModel(headers, dsNV);
    	tblNhanVien.setModel(nhanVienTableModel);
    	tblNhanVien.updateUI();
    }
    private void updateComboboxTinh() {
		List<String> dsTam = diaChiDAO.layDanhSachTinh();

		String[] dsTinh = new String[dsTam.size()];
		dsTam.toArray(dsTinh);
		cmbTinhTP.setModel(new DefaultComboBoxModel<String>(dsTinh));
		cmbTinhTP.updateUI();
		updateComboboxHuyen();
	}
    

	private void updateComboboxHuyen() {
		String tinh = (String) cmbTinhTP.getSelectedItem();
	    List<String> dsTam = diaChiDAO.layDSHuyenTheoTinh(tinh);
	    String[] dsHuyen = new String[dsTam.size()];
	    dsTam.toArray(dsHuyen);
	    cmbQuanHuyen.setModel(new DefaultComboBoxModel<String>(dsHuyen));
	    cmbQuanHuyen.updateUI();

	    updateComboboxXa();
	}
	
	private void updateComboboxXa() {
	    String tinh = (String) cmbTinhTP.getSelectedItem();
	    String huyen = (String) cmbQuanHuyen.getSelectedItem();
	    List<String> dsTam = diaChiDAO.layDSXaTheoHuyenTinh(tinh, huyen);
	    String[] dsXa = new String[dsTam.size()];
	    dsTam.toArray(dsXa);
	    cmbPhuongXa.setModel(new DefaultComboBoxModel<String>(dsXa));
	    cmbPhuongXa.updateUI();
	}
    private void xoaRong() {
    	txtTenNhanVien.setText("");
    	txtMaNhanVien.setText("");
    	txtSoDienThoai.setText("");
    	txtEmail.setText("");
//		cmbVaiTro.setSelectedItem("Nhân Viên");
//		cmbGioiTinh.setSelectedItem("Nam");
		dtNgaySinh.setDate(null);
		dtNgayVaoLam.setDate(null);
		lblAnhDaiDien.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + "noimage.png"));
//		lbAnh.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + "noimage.png")); // NOI18N
//		lbAnh.updateUI();
//		btnXoa.setEnabled(false);
//		btnSua.setEnabled(false);
//		tbNV.getCellEditor().stopCellEditing();
	}
    private void batTextfield() {
    	txtMaNhanVien.setEditable(true);
    	txtTenNhanVien.setEditable(true);
    	txtEmail.setEditable(true);
    	txtSoDienThoai.setEditable(true);
    	cmbGioiTinh.setEnabled(true);
    	cmbVaiTro.setEnabled(true);
    	cmbTinhTP.setEnabled(true);
    	cmbQuanHuyen.setEnabled(true);
    	cmbPhuongXa.setEnabled(true);
    	dtNgaySinh.setEnabled(true);
    	dtNgayVaoLam.setEnabled(true);
    	btnChonHinhAnh.setEnabled(true);
//    	dtNgaySinh.setEdit
//    	updateComboboxTinh();


    	
    }
    private void tatTextfield() {
    	txtMaNhanVien.setEditable(false);
    	txtTenNhanVien.setEditable(false);
    	txtEmail.setEditable(false);
    	txtSoDienThoai.setEditable(false);
    	cmbGioiTinh.setEnabled(false);
    	cmbVaiTro.setEnabled(false);
    	cmbTinhTP.setEnabled(false);
    	cmbQuanHuyen.setEnabled(false);
    	cmbPhuongXa.setEnabled(false);
    	dtNgaySinh.setEnabled(false);
    	dtNgayVaoLam.setEnabled(false);
    	btnChonHinhAnh.setEnabled(false);
    }
    private NhanVien getDuLieuTuTextField() throws Exception {
		String maNV = txtMaNhanVien.getText().trim();
//		sau se check regex
		String tenNV = txtTenNhanVien.getText().trim();
		//sau se check regex
		String soDienThoai = txtSoDienThoai.getText().trim();
		//sau se check regex
		String email = txtEmail.getText().trim();
		Date ngaySinh = null;
		try {
			ngaySinh = dtNgaySinh.getDate();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		Date ngayVaoLam = null;
		try {
			ngayVaoLam = dtNgayVaoLam.getDate();
		} catch (Exception e) {
			// TODO: handle exception
		}
		if(ngayVaoLam.getYear() - ngaySinh.getYear() < 18)
		{
			JOptionPane.showMessageDialog(null, "Nhân viên phải từ 18 tuổi trở lên");
			return null;
		}
		
		String gioiTinh = cmbGioiTinh.getSelectedItem().toString();
		String vaiTro = cmbVaiTro.getSelectedItem().toString();
		DiaChi diaChi = diaChiDAO.getDiaChiTheoTinhHuyenXa(cmbTinhTP.getSelectedItem().toString()
				, cmbQuanHuyen.getSelectedItem().toString()
				, cmbPhuongXa.getSelectedItem().toString());
		String hinhAnh  = lblAnhDaiDien.getIcon().toString();
		//xoa duong dan tuyet doi cua link anh va thay bang duong dan tuong doi trong project
		hinhAnh = hinhAnh.replace(PathSetting.PATH_IMAGE_NHANVIEN,"" );
		NhanVien nhanVien = new NhanVien(maNV, tenNV, ngaySinh, email, soDienThoai, diaChi, ngayVaoLam, gioiTinh, vaiTro, hinhAnh);
		
		return nhanVien;
		
		
		
		
	}
//    private String lamMoiHuyen(String tinhDangChon) {
//    	
//    }
    
    private void themSuKien() {
    	dsNV = nhanVienDAO.layDanhSachNhanVien();
        updateModelTable(dsNV, HEADERS);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
			tblNhanVien.getColumnModel().getColumn(5).setMinWidth(320);

		}
        
        
        tblNhanVien.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				String item = (String) tblNhanVien.getModel().getValueAt(tblNhanVien.getSelectedRow(), 0);
				if (item != null) {
					NhanVien nv = null;
					try {
						if(!trangThaiThem) {
							
							nv = nhanVienDAO.timNhanVienBangMaNhanVien(item);
							fillThongTinNhanVien(nv);
						}
					} catch (Exception e1) {
						e1.printStackTrace();
					}

				}
			}

			private void fillThongTinNhanVien(NhanVien nv) throws Exception {
				// TODO Auto-generated method stub
				txtTenNhanVien.setText(nv.getTenNhanVien());
//				tfDiaChi.setText(nv.getDiaChi());
				txtMaNhanVien.setText(nv.getMaNhanVien());
				txtSoDienThoai.setText(nv.getSoDienThoai());
//				cmbTinhTP.addItem(nv.getDiaChi().getTinhTP());
				cmbTinhTP.setSelectedItem(nv.getDiaChi().getTinhTP());
				cmbQuanHuyen.addItem(nv.getDiaChi().getQuanHuyen());
				cmbQuanHuyen.setSelectedItem(nv.getDiaChi().getQuanHuyen());
				cmbPhuongXa.addItem(nv.getDiaChi().getPhuongXa());
				cmbPhuongXa.setSelectedItem(nv.getDiaChi().getPhuongXa());
//				cmbVaiTro.addItem(nv.getVaiTro());
				cmbVaiTro.setSelectedItem(nv.getVaiTro());
				cmbGioiTinh.setSelectedItem(nv.getGioiTinh().compareTo("Nữ") == 0?"Nữ": "Nam" );
				txtEmail.setText(nv.getEmail());
				dtNgaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgaySinh().toString()));
				dtNgayVaoLam.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgayVaoLam().toString()));
				lblAnhDaiDien.setIcon(new ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + nv.getAnhDaiDien()));
//				System.out.println(PathSetting.PATH_IMAGE_NHANVIEN + nv.getAnhDaiDien());
//				System.out.println(PathSetting.PATH_TO_PACKAGE);
//				lbAnh.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + nv.getLinkAnhNV())); // NOI18N
//				lbAnh.updateUI();
			}
			
		});
        //cap nhat lai combobox Huyen sau khi combobox tinh duoc sele
        cmbTinhTP.addPopupMenuListener(new PopupMenuListener() {

			
			@Override
			public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				updateComboboxHuyen();
				
			}

			@Override
			public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void popupMenuCanceled(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				
			}
			
		});
        //cap nhat lai combobox xa sau khi combobox huyen duoc selected
        cmbQuanHuyen.addPopupMenuListener(new PopupMenuListener() {
			
			@Override
			public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				
				
			}
			
			@Override
			public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				updateComboboxXa();
				
				
			}
			
			@Override
			public void popupMenuCanceled(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
        //bat su kien nut them
        btnThem.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnThemActionPerformed(e);
//					tblNhanVien.setEnabled(true);
				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
				
			}
			private void btnThemActionPerformed(ActionEvent evt){
		    	updateComboboxTinh();
				xoaRong();
				batTextfield();
				trangThaiThem = true;
		        pnlChucNangTo.removeAll();
		        pnlChucNangTo.setLayout(new BorderLayout());
		        PanelXacNhan pnlXacNhan = new PanelXacNhan();
		        pnlChucNangTo.add(pnlXacNhan);	
		
		        ActionListener listenerHuy = new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                System.out.println("ok");
		            	trangThaiThem = false;
		                pnlChucNangTo.removeAll();
		                pnlChucNangTo.setLayout(new BorderLayout());
		                pnlChucNangTo.add(pnlChucNang);
		                pnlChucNangTo.updateUI();
//		                tatTextfield();
		            }
		        };
		        ActionListener listenerThem = new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
//						NhanVien nhanVien = null;
						try {
							NhanVien nhanVien = getDuLieuTuTextField();
							if(nhanVien != null) {
								nhanVienDAO.themNhanVien(nhanVien);
								if(nhanVien.getVaiTro().equalsIgnoreCase("Quản lý") || nhanVien.getVaiTro().equalsIgnoreCase("Kế toán")) {
									String tenTK = nhanVien.getMaNhanVien();
									String matKhau = "123456";
									TaiKhoan taiKhoan  = new TaiKhoan(tenTK, matKhau, nhanVien.getVaiTro(), nhanVien);
									taiKhoanDAO.themTaiKhoan(taiKhoan);
									
								}
								dsNV = nhanVienDAO.layDanhSachNhanVien();
								updateModelTable(dsNV, HEADERS);
								xoaRong();
								JOptionPane.showMessageDialog(null, "Thêm thành công");
								
							}
						} catch (Exception e2) {
							e2.printStackTrace();
							// TODO: handle exception
						}
						
					}
				};
				
		        pnlXacNhan.huyAddActionListener(listenerHuy);
		        pnlXacNhan.xacNhanAddActionListener(listenerThem);
		        pnlChucNangTo.repaint();
		        pnlChucNangTo.revalidate();
				
				
			
			}
			
			

		});
        
        btnXoa.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				try {
					btnXoaActionPerformed(e);
				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
				
			}
		    private void btnXoaActionPerformed(ActionEvent evt) {
		        // TODO add your handling code here:
		    	try {
					String maNV = (String) tblNhanVien.getModel().getValueAt(tblNhanVien.getSelectedRow(), 0);
					int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa không", "Xóa",
							JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
					if(luaChon == JOptionPane.YES_OPTION ) {
						boolean ketQua = nhanVienDAO.xoaNhanVien(maNV);
						if(ketQua) {
							
							//cap nhat lai bang nhan vien
							dsNV = nhanVienDAO.layDanhSachNhanVien();
							updateModelTable(dsNV, HEADERS);
							xoaRong();
							JOptionPane.showMessageDialog(null, "Xóa thành công");

							
						}
						else {
							
							JOptionPane.showMessageDialog(null, "Xóa thất bại");
							xoaRong();
						}

					}
					
				} catch (Exception e) {
					// TODO: handle exception
					e.printStackTrace();
				}
		    	
		    }
		});
		btnSua.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				btnSuaActionPerformed(evt);
			}
		    private void btnSuaActionPerformed(ActionEvent evt) {
		        // TODO add your handling code here:
		    	
		    	batTextfield();
		    	String huyenDangChon = cmbQuanHuyen.getSelectedItem().toString();
		    	String xaDangChon = cmbPhuongXa.getSelectedItem().toString();
//		    	lamMoiHuyen(tinhDangChon);
		    	
//		    	lamMoiXa(huyenDangChon);
		    	updateComboboxHuyen();
		    	
		    	cmbQuanHuyen.setSelectedItem(huyenDangChon);
		    	updateComboboxXa();
		    	cmbPhuongXa.setSelectedItem(xaDangChon);
//				trangThaiThem = true;
		        pnlChucNangTo.removeAll();
		        pnlChucNangTo.setLayout(new BorderLayout());
		        PanelXacNhan pnlXacNhan = new PanelXacNhan();
		        pnlChucNangTo.add(pnlXacNhan);
		
		        ActionListener listenerHuy = new ActionListener() {
		            public void actionPerformed(ActionEvent evt) {
		                System.out.println("ok");
		            	trangThaiThem = false;
		                pnlChucNangTo.removeAll();
		                pnlChucNangTo.setLayout(new BorderLayout());
		                pnlChucNangTo.add(pnlChucNang);
		                pnlChucNangTo.updateUI();
		                tatTextfield();
		            }
		        };
		        
		        ActionListener listenerSua = new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
						try {
							NhanVien nhanVien = getDuLieuTuTextField();
						
							if(nhanVien != null) {
								nhanVienDAO.capNhatNhanVien(nhanVien);
								dsNV = nhanVienDAO.layDanhSachNhanVien();
								updateModelTable(dsNV, HEADERS);
								JOptionPane.showMessageDialog(null, "Cập nhật thành công");
							}
							
						} catch (Exception e2) {
							// TODO: handle exception
							e2.printStackTrace();
						}
						
					}
					
				};
		        pnlXacNhan.huyAddActionListener(listenerHuy);
		        pnlXacNhan.xacNhanAddActionListener(listenerSua);
		        pnlChucNangTo.repaint();
		        pnlChucNangTo.revalidate();

		    	
		    }
		});
		btnTimKiem.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemActionPerformed(e);
				
			}
		    private void btnTimKiemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		    	batTextfield();
		    	xoaRong();

				trangThaiThem = true;
		        pnlChucNangTo.removeAll();
		        pnlChucNangTo.setLayout(new BorderLayout());
		        PanelXacNhan pnlXacNhan = new PanelXacNhan();
		        pnlChucNangTo.add(pnlXacNhan);
		
		        ActionListener listenerHuy = new ActionListener() {
		            public void actionPerformed(ActionEvent evt) {
//		                System.out.println("ok");
		            	trangThaiThem = false;
		                pnlChucNangTo.removeAll();
		                pnlChucNangTo.setLayout(new BorderLayout());
		                pnlChucNangTo.add(pnlChucNang);
		                pnlChucNangTo.updateUI();
		                tatTextfield();
		            }
		        };
		        
		        ActionListener listenerTimKiem = new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
						try {
							NhanVien nhanVien = getDuLieuTuTextField();
							
							
						 	
							if(nhanVien != null) {
								nhanVienDAO.capNhatNhanVien(nhanVien);
								dsNV = nhanVienDAO.layDanhSachNhanVien();
								updateModelTable(dsNV, HEADERS);
								JOptionPane.showMessageDialog(null, "Cập nhật thành công");
							}
							
						} catch (Exception e2) {
							// TODO: handle exception
							e2.printStackTrace();
						}
						
					}
					
				};
		        pnlXacNhan.huyAddActionListener(listenerHuy);
		        pnlXacNhan.xacNhanAddActionListener(listenerTimKiem);
		        pnlChucNangTo.repaint();
		        pnlChucNangTo.revalidate();

		    	
		    }
			
		});
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQLNV = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        cmbTinhTP = new javax.swing.JComboBox<>();
        cmbQuanHuyen = new javax.swing.JComboBox<>();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        dtNgaySinh = new com.toedter.calendar.JDateChooser();
        dtNgayVaoLam = new com.toedter.calendar.JDateChooser();
        lblTieuDe = new javax.swing.JLabel();
        lblAnhDaiDien = new javax.swing.JLabel();
        cmbVaiTro = new javax.swing.JComboBox<>();
        scrTableNhanVien = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnChonHinhAnh = new javax.swing.JButton();
        pnlChucNangTo = new javax.swing.JPanel();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        cmbPhuongXa = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlQLNV.setBackground(new java.awt.Color(255, 255, 255));
        pnlQLNV.setPreferredSize(new java.awt.Dimension(1250, 475));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên:");

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên:");

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoDienThoai.setText("Số điện thoại:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtTenNhanVien.setEditable(false);
        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNhanVien.setBorder(null);
        txtTenNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtSoDienThoai.setEditable(false);
        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
//        txtEmail.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtEmailActionPerformed(evt);
//            }
//        });
        txtEmail.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGioiTinh.setText("Giới tính:");

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh:");

        lblNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayVaoLam.setText("Ngày vào làm:");

        lblVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVaiTro.setText("Vai trò:");

        cmbTinhTP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tỉnh/Thành phố" }));
        cmbTinhTP.setEnabled(false);

        cmbQuanHuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbQuanHuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận/Huyện" }));
        cmbQuanHuyen.setEnabled(false);

        cmbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioiTinh.setEnabled(false);

        dtNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        dtNgaySinh.setEnabled(false);
        dtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        dtNgayVaoLam.setBackground(new java.awt.Color(255, 255, 255));
        dtNgayVaoLam.setEnabled(false);
        dtNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("QUẢN LÝ NHÂN VIÊN");

        lblAnhDaiDien.setBackground(new java.awt.Color(0, 204, 153));
        lblAnhDaiDien.setForeground(new java.awt.Color(0, 255, 204));

        cmbVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Kế toán", "Nhân viên" }));
        cmbVaiTro.setEnabled(false);

        scrTableNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        scrTableNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã công nhân", "Tên công nhân", "Số điện thoại", "Email", "Địa chỉ", "Giới tính", "Ngày sinh", "Ngày vào làm", "Tổ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setSelectionBackground(new java.awt.Color(232, 57, 95));
//        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                tblNhanVienMouseClicked(evt);
//            }
//        });
        scrTableNhanVien.setViewportView(tblNhanVien);

        btnChonHinhAnh.setText("Hình ảnh");
        btnChonHinhAnh.setEnabled(false);

        pnlChucNangTo.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNangTo.setLayout(new java.awt.BorderLayout());

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNang.setPreferredSize(new java.awt.Dimension(698, 57));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-20.png"))); // NOI18N
        btnThem.setText("Thêm");
//        btnThem.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnThemActionPerformed(evt);
//            }
//        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
//        btnSua.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSuaActionPerformed(evt);
//            }
//        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
//        btnXoa.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnXoaActionPerformed(evt);
//            }
//        });

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
//        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnTimKiemActionPerformed(evt);
//            }
//        });

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTimKiem))
                .addContainerGap())
        );

        pnlChucNangTo.add(pnlChucNang, java.awt.BorderLayout.CENTER);

        cmbPhuongXa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPhuongXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phường/Xã" }));
        cmbPhuongXa.setEnabled(false);

        javax.swing.GroupLayout pnlQLNVLayout = new javax.swing.GroupLayout(pnlQLNV);
        pnlQLNV.setLayout(pnlQLNVLayout);
        pnlQLNVLayout.setHorizontalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblSoDienThoai)
                            .addComponent(lblDiaChi)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblTenNhanVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addComponent(cmbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cmbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                    .addComponent(txtSoDienThoai)
                                    .addComponent(txtTenNhanVien)
                                    .addComponent(txtMaNhanVien))
                                .addGap(44, 44, 44)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNgaySinh)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(lblNgayVaoLam)
                                    .addComponent(lblVaiTro))
                                .addGap(31, 31, 31)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))
                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                        .addComponent(pnlChucNangTo, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)))
                .addGap(224, 224, 224))
            .addComponent(scrTableNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlQLNVLayout.setVerticalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNhanVien)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenNhanVien))
                                .addGap(20, 20, 20)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoDienThoai))
                                .addGap(18, 18, 18)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGap(26, 26, 26)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaChi)
                                    .addComponent(cmbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pnlChucNangTo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblNgaySinh))
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblNgayVaoLam))
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVaiTro)
                                    .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonHinhAnh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTableNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 1637, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtEmailActionPerformed

//    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
//
//    }//GEN-LAST:event_tblNhanVienMouseClicked

//    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        pnlChucNangTo.removeAll();
//        pnlChucNangTo.setLayout(new BorderLayout());
//        PanelXacNhan pnlXacNhan = new PanelXacNhan();
//        pnlChucNangTo.add(pnlXacNhan);
//
//        ActionListener listenerHuy = new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                System.out.println("ok");
//                pnlChucNangTo.removeAll();
//                pnlChucNangTo.setLayout(new BorderLayout());
//                pnlChucNangTo.add(pnlChucNang);
//                pnlChucNangTo.updateUI();
//            }
//        };
//        pnlXacNhan.huyAddActionListener(listenerHuy);
//        pnlChucNangTo.repaint();
//        pnlChucNangTo.revalidate();
//    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

//    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnXoaActionPerformed

//    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinhAnh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbPhuongXa;
    private javax.swing.JComboBox<String> cmbQuanHuyen;
    private javax.swing.JComboBox<String> cmbTinhTP;
    private javax.swing.JComboBox<String> cmbVaiTro;
    private com.toedter.calendar.JDateChooser dtNgaySinh;
    private com.toedter.calendar.JDateChooser dtNgayVaoLam;
    private javax.swing.JLabel lblAnhDaiDien;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlChucNangTo;
    private javax.swing.JPanel pnlQLNV;
    private javax.swing.JScrollPane scrTableNhanVien;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
